#! /bin/bash
# trap signals
trap '' 2
# Import Color Functions
source ./Utilities/ColorsFuncs
# Import Utility Functions
# Run the input handling function in the background
source ./Utilities/Functions
# Welcome message here
echo "        ════════════════════════════════"
echo "         ══════════════════════════════"
echo " ══════════════════════════════════════════════"
echo "  ════════════════════════════════════════════"
echo "   ══════════════════════════════════════════"
cat ./Utilities/Welcome
echo "    ════════════════════════════════════════"
echo "     ══════════════════════════════════════"
echo "      ════════════════════════════════════"
echo "       ══════════════════════════════════"
echo "══════════════════════════════════════════════════"


# Initialization of Database
DB_PATH="./BASHDBS"
if [ ! -d "$DB_PATH" ]; then
  echo ".............Initializing Your Files,First Time!!............."
  mkdir "$DB_PATH"
fi
# Breif message here
echo "╔════════════════════════════════════════════════╗"
printf "║\e[1;38;2;255;255;255m\e[48;2;128;0;128m %+30s %-15s \e[0m║\n" "Summary" 
printf "║\e[1;38;2;0;0;0m\e[48;2;211;211;211m %-30s ║ %-13s \e[0m║\n" "DataBases" "Tables"
echo "╟────────────────────────────────────────────────╢"

for dir in "$DB_PATH"/*; do
    if [ -d "$dir" ]; then
        db_count=$(find "$dir" -type f -name "*.db" | wc -l)
        printf "║\e[1;34;46m %-30s ║ %-13s \e[0m║\n" "$(basename "$dir"):" "$db_count"
    fi
done

echo "╚════════════════════════════════════════════════╝"

# manage databases menu
entry_menu(){
while true; do
echo -ne "
What Do you want to DO?
$(Red '1) Create DataBase') 
$(Red '2) Connect DataBase')
$(Red '3) List DataBases')
$(Red '4) Drop DataBases')
$(Red '5) Exit')
$(RedB 'Choose an option:')
"
read entry
case $entry in
        # Create Database Option
        1) cd "$DB_PATH";
	while true; do
                echo "Enter Your New DataBase Name: ";
                read dbn;
                test_dbn=$(check_name "$dbn")
                if [ $test_dbn -eq "1" ]; then
                        echo "Naming Error please Enter only English Alphapet"; continue
                elif [ -d "$dbn" ]; then
                        echo "DataBase Already Exists , Enter a new Name;"; continue
                else
                        echo "...........Creating you DataBase ............"
                        mkdir "$dbn"
                        break
                fi
        done
        cd ../ ;;
        # Connect to Database Option
        2) cd "$DB_PATH"
        while true; do
                echo "Enter Your DataBase Name: ";
                read dbn2;
                test_dbn=$(check_name "$dbn2")
                if [ $test_dbn -eq "1" ]; then 
                        echo "Naming Error please Enter only English Alphapet"; continue
                elif [ ! -d "$dbn2" ]; then
                        echo "DataBase Does Not Exists!! Did You Enter name Correctly: ;"; continue
                else
                        echo "...........Connecting you to DataBase $dbn2 ............"
                        cd "$dbn2"
                        # Start Table Menu 
                        while true; do
echo -ne "
What Do you want to DO?
$(Red '1) Create Table') 
$(Red '2) Insert into Table')
$(Red '3) List Tables')
$(Red '4) Drop Table')
$(Red '5) Select From Table')
$(Red '6) Delete Table')
$(Red '7) Update Table')
$(Red '8) Exit')
$(RedB 'Choose an option:')
"
                                read table
                                case $table in
                                        # Create Table Option
                                        1) source ../../Scripts/CreateTable;;
                                        2) source ../../Scripts/InsertTable;;
                                        3) source ../../Scripts/ListTable  ;;
                                        4) source ../../Scripts/DropTable  ;;
                                        5) source ../../Scripts/SelectTable;;
                                        6) source ../../Scripts/DeleteTable;;
                                        7) source ../../Scripts/UpdateTable;;
                                        8) break;;
                                esac
                        done
                        break
                fi
        done
        cd ../../ ;;
        # List Databases Option
        3) cd "$DB_PATH"
        echo -ne "$(ls -d */ | sed 's#/##') \n"
        cd ../ ;;
        # Delete Database Option
        4) cd "$DB_PATH"
        while true; do
                echo "Enter Your DataBase Name: ";
                read dbn3;
                test_dbn=$(check_name "$dbn3")
                if [ $test_dbn -eq "1" ]; then
                        echo "Naming Error please Enter only English Alphapet"; continue
                elif [ ! -d "$dbn3" ]; then
                        echo "DataBase Does Not Exists!! Did You Enter name Correctly: ;"; continue
                else
                        echo "...........Droping Your DataBase $dbn3 ............"
                        rm -r "$dbn3"
                        break
                fi
        done
        cd ../ ;;
        # Exit Database Option
        5) break;;
        *) echo -ne "$(RedB "Ooops - unknown choice $a")"; continue;
esac
done
}
echo "Press a key.... ('q' to Quit, 'c' to continue):"

while true; do
    read -rsn 1 key
    case "$key" in
        [qQ]) break ;;
        [cC]) entry_menu;;
        *) ;;
    esac
done


echo "        ════════════════════════════════"
echo "         ══════════════════════════════"
echo " ══════════════════════════════════════════════"
echo "  ════════════════════════════════════════════"
echo "   ══════════════════════════════════════════"
cat ./Utilities/GoodBye
echo "    ════════════════════════════════════════"
echo "     ══════════════════════════════════════"
echo "      ════════════════════════════════════"
echo "       ══════════════════════════════════"
echo "══════════════════════════════════════════════════"

# End Trapping 
trap 2
