#! /usr/bin/bash

# Declare Advanced Regex
shopt -s extglob

# check names to contain only alpha characters
check_name () {
if [[ $1 =~ ^[a-zA-Z]+$ ]]; then
  echo 0
else
  echo 1
fi
}
#read x
#test_name=$(check_name "$x")

#check value is not null
not_null () {
if [ ! -z "$1" ]; then
  echo 0
else
  echo 1
fi
}
#test_result=$(not_null "$x")

# check value is only numbers
only_numbers (){
if [[ $1 =~ ^[0-9]+$ ]]; then
  echo 0
else
  echo 1
fi
}

# check if a value exists in an array
in_array() {
    local value="$1"
    shift
    local array=("$@")
    for item in "${array[@]}"; do
        if [ "$item" == "$value" ]; then
            echo "0"  # Return "0" for success (value found)
            return
        fi
    done
    echo "1"  # Return "1" for failure (value not found)
}
